package com.contextextractor.infrastructure.export;

import com.contextextractor.domain.model.ContextPayload;
import com.contextextractor.domain.model.TableConfig;
import com.contextextractor.domain.strategy.ContextExportStrategy;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;

public class XmlContextExporter implements ContextExportStrategy {

    @Override
    public List<Path> export(ContextPayload payload, Path outputDirectory) throws IOException {
        List<Map.Entry<String, String>> allFileEntries = new ArrayList<>(payload.files().entrySet());
        String singleXml = buildPartXml(payload, allFileEntries, true, true);
        byte[] singleBytes = singleXml.getBytes(StandardCharsets.UTF_8);
        long maxBytes = (long) payload.settings().maxXmlSizeMb() * 1024 * 1024;

        if (singleBytes.length <= maxBytes) {
            String baseName = (payload.outputFileName() != null && !payload.outputFileName().isBlank())
                    ? payload.outputFileName().replaceAll("[^a-zA-Z0-9_\\-]", "_")
                    : "context";
            Path out = resolveOutputPath(outputDirectory, baseName + ".xml");
            Files.writeString(out, singleXml, StandardCharsets.UTF_8);
            return List.of(out);
        }

        return splitExport(payload, allFileEntries, outputDirectory, maxBytes);
    }

    private List<Path> splitExport(ContextPayload payload,
                                    List<Map.Entry<String, String>> allFileEntries,
                                    Path outputDirectory, long maxBytes) throws IOException {
        String emptyPart = buildPartXml(payload, List.of(), true, true);
        long overhead = emptyPart.getBytes(StandardCharsets.UTF_8).length;

        List<List<Map.Entry<String, String>>> parts = new ArrayList<>();
        List<Map.Entry<String, String>> currentPart = new ArrayList<>();
        long currentSize = overhead;

        for (Map.Entry<String, String> entry : allFileEntries) {
            long fileSize = buildFileXml(entry).getBytes(StandardCharsets.UTF_8).length;
            if (!currentPart.isEmpty() && currentSize + fileSize > maxBytes) {
                parts.add(currentPart);
                currentPart = new ArrayList<>();
                currentSize = overhead;
            }
            currentPart.add(entry);
            currentSize += fileSize;
        }
        if (!currentPart.isEmpty() || parts.isEmpty()) {
            parts.add(currentPart);
        }

        List<Path> result = new ArrayList<>();
        for (int i = 0; i < parts.size(); i++) {
            boolean isFirst = i == 0;
            boolean isLast = i == parts.size() - 1;
            String xml = buildPartXml(payload, parts.get(i), isFirst, isLast);
            String bn = (payload.outputFileName() != null && !payload.outputFileName().isBlank())
                    ? payload.outputFileName().replaceAll("[^a-zA-Z0-9_\\-]", "_")
                    : "context";
            String filename = parts.size() == 1 ? bn + ".xml" : bn + "-part" + (i + 1) + ".xml";
            Path out = resolveOutputPath(outputDirectory, filename);
            Files.writeString(out, xml, StandardCharsets.UTF_8);
            result.add(out);
        }
        return result;
    }

    private String buildPartXml(ContextPayload payload,
                                 List<Map.Entry<String, String>> fileEntries,
                                 boolean includeDatabase,
                                 boolean includeAdditionalContext) {
        StringBuilder sb = new StringBuilder();
        String generatedAt = LocalDateTime.now().format(DateTimeFormatter.ISO_LOCAL_DATE_TIME);
        String presetName = payload.presetName() != null ? payload.presetName() : "unsaved";

        sb.append("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n");
        sb.append("<!--\n");
        sb.append("    Generated by Context Extractor — a developer tool for assembling AI context files.\n");
        sb.append("\n");
        sb.append("    HOW TO READ THIS FILE\n");
        sb.append("    ─────────────────────────────────────────────────────────────────────────────\n");
        sb.append("    This document bundles everything a developer has chosen to share with you\n");
        sb.append("    into a single structured file. Read all sections before responding.\n");
        sb.append("\n");
        sb.append("    <agent>\n");
        sb.append("        The system prompt or role instructions written by the developer.\n");
        sb.append("        This defines your persona, task, and constraints. Treat it as your\n");
        sb.append("        primary directive for the entire conversation.\n");
        sb.append("\n");
        sb.append("    <files>\n");
        sb.append("        Source code and text files from a project directory. Each <file>\n");
        sb.append("        has a path attribute (relative to the scanned root directory) and\n");
        sb.append("        its full content in a CDATA block. Use the path to understand the\n");
        sb.append("        module structure and package layout of the project.\n");
        sb.append("\n");
        sb.append("    <database schema=\"...\">\n");
        sb.append("        PostgreSQL database information for the named schema. Each <table>\n");
        sb.append("        may contain:\n");
        sb.append("          <ddl>   — the CREATE TABLE statement with all column types,\n");
        sb.append("                    constraints, and indexes. Use this to understand the\n");
        sb.append("                    exact data model.\n");
        sb.append("          <data>  — sample rows as <row> elements with <col name=\"...\">.\n");
        sb.append("                    Use these to understand realistic data shapes and values.\n");
        sb.append("\n");
        sb.append("    <additionalContext>\n");
        sb.append("        Free-form notes written by the developer: business rules, known\n");
        sb.append("        issues, architectural decisions, or explicit instructions to you.\n");
        sb.append("        Treat this as high-priority context that can override or extend\n");
        sb.append("        anything else in this file.\n");
        sb.append("\n");
        sb.append("    CDATA BLOCKS\n");
        sb.append("        All dynamic content (code, DDL, free text) is wrapped in\n");
        sb.append("        <![CDATA[ ... ]]> to prevent XML parsing conflicts. The content\n");
        sb.append("        inside should be interpreted literally, not as XML.\n");
        sb.append("\n");
        sb.append("    MULTI-PART FILES\n");
        sb.append("        If the output was split due to size limits, you will receive\n");
        sb.append("        context-part1.xml, context-part2.xml, etc. Each part is a valid\n");
        sb.append("        XML document. Process all parts before responding — the <files>\n");
        sb.append("        section is distributed across parts while <agent>, <database>,\n");
        sb.append("        and <additionalContext> appear only in the relevant part.\n");
        sb.append("    ─────────────────────────────────────────────────────────────────────────────\n");
        sb.append("-->\n");
        sb.append("<context")
          .append(" generated-at=\"").append(generatedAt).append("\"")
          .append(" preset=\"").append(escapeAttr(presetName)).append("\"")
          .append(" generator=\"context-extractor/1.0.0\">\n\n");

        if (payload.agentContent() != null && !payload.agentContent().isBlank()) {
            sb.append("    <agent>\n");
            sb.append("        <![CDATA[\n");
            sb.append(escapeCdata(payload.agentContent()));
            sb.append("\n        ]]>\n");
            sb.append("    </agent>\n\n");
        }

        sb.append("    <files>\n");
        for (Map.Entry<String, String> entry : fileEntries) {
            sb.append(buildFileXml(entry));
        }
        sb.append("\n    </files>\n\n");

        if (includeDatabase && payload.databaseConfig() != null
                && (!payload.tableDdl().isEmpty() || !payload.tableData().isEmpty())) {
            sb.append("    <database schema=\"")
              .append(escapeAttr(payload.databaseConfig().schema())).append("\">\n\n");

            for (TableConfig tc : payload.tables()) {
                boolean hasDdl = tc.exportDdl() && payload.tableDdl().containsKey(tc.tableName());
                boolean hasData = tc.exportData() && payload.tableData().containsKey(tc.tableName());
                if (!hasDdl && !hasData) continue;

                sb.append("        <table name=\"").append(escapeAttr(tc.tableName())).append("\">\n\n");

                if (hasDdl) {
                    sb.append("            <ddl>\n");
                    sb.append("                <![CDATA[\n");
                    sb.append(escapeCdata(payload.tableDdl().get(tc.tableName())));
                    sb.append("\n                ]]>\n");
                    sb.append("            </ddl>\n\n");
                }

                if (hasData) {
                    List<Map<String, String>> rows = payload.tableData().get(tc.tableName());
                    sb.append("            <data rows=\"").append(rows.size()).append("\">\n");
                    for (Map<String, String> row : rows) {
                        sb.append("                <row>\n");
                        for (Map.Entry<String, String> col : row.entrySet()) {
                            sb.append("                    <col name=\"")
                              .append(escapeAttr(col.getKey())).append("\">")
                              .append(escapeContent(col.getValue()))
                              .append("</col>\n");
                        }
                        sb.append("                </row>\n");
                    }
                    sb.append("            </data>\n\n");
                }

                sb.append("        </table>\n\n");
            }

            sb.append("    </database>\n\n");
        }

        if (includeAdditionalContext
                && payload.additionalContext() != null
                && !payload.additionalContext().isBlank()) {
            sb.append("    <additionalContext>\n");
            sb.append("        <![CDATA[\n");
            sb.append(escapeCdata(payload.additionalContext()));
            sb.append("\n        ]]>\n");
            sb.append("    </additionalContext>\n\n");
        }

        sb.append("</context>\n");
        return sb.toString();
    }

    private String buildFileXml(Map.Entry<String, String> entry) {
        StringBuilder sb = new StringBuilder();
        sb.append("\n        <file path=\"").append(escapeAttr(entry.getKey())).append("\">\n");
        sb.append("            <![CDATA[\n");
        sb.append(escapeCdata(entry.getValue()));
        sb.append("\n            ]]>\n");
        sb.append("        </file>\n");
        return sb.toString();
    }

    private Path resolveOutputPath(Path directory, String filename) {
        Path out = directory.resolve(filename);
        if (Files.exists(out)) {
            String timestamp = LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyyMMdd-HHmmss"));
            int dot = filename.lastIndexOf('.');
            String base = dot >= 0 ? filename.substring(0, dot) : filename;
            String ext = dot >= 0 ? filename.substring(dot) : "";
            out = directory.resolve(base + "-" + timestamp + ext);
        }
        return out;
    }

    private String escapeCdata(String s) {
        if (s == null) return "";
        return s.replace("]]>", "]]]]><![CDATA[>");
    }

    private String escapeAttr(String s) {
        if (s == null) return "";
        return s.replace("&", "&amp;").replace("<", "&lt;").replace("\"", "&quot;");
    }

    private String escapeContent(String s) {
        if (s == null) return "";
        return s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;");
    }
}
